version: "3"

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: tnews
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
    expose:
      - '3306'
    command: --init-file /app/tnews.sql  
    volumes:
      - .:/app
  app:
    depends_on:
      - db
    build: .
    command: node ./app/tnews/bin/www
    ports:
      - "5000:5000"
    volumes:
      - .:/app

    environment:
      DBHOST: db
      DBPORT: 3306
      DBUSER: root
      DBPASS: password
      
# Names our volume
volumes:
  my-db:
